# truncate the csv for now
def truncatecsv(config_details):
    f1 = open(config_details["json_queries"], "w")
    f1.truncate()
    f1.close()
    f2 = open(config_details["json_wb"], "w")
    f2.truncate()
    f2.close()
    f3 = open(config_details["json_ds"], "w")
    f3.truncate()
    f3.close()
    f4 = open(config_details["json_tables"], "w")
    f4.truncate()
    f4.close()
    f5 = open(config_details["json_databases"], "w")
    f5.truncate()
    f5.close()
    f6 = open(config_details["json_columns"], "w")
    f6.truncate()
    f6.close()